- name: Install Packages PHP7
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php
    - php7.0-dev
    - php7.0-zip
    - php7.0-gd
    - php7.0-dom
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-intl
    - php7.0-mbstring
    - php7.0-mysqlnd
    - php-fpm

- name: php-fpm - magento2
  sudo: yes
  template: src=php-fpm-magento2.conf
            dest=/etc/php/7.0/fpm/pool.d/magento2.conf
  notify: reload php-fpm

- include: xdebug.yml
