---
- name: Set up a LEMP7 stack for Magento2 on Ubuntu 16.04
  hosts: vagrant
  become: no
  become_user: root
  remote_user: ubuntu
  vars_files:
    - env_vars/base.yml
  roles:
    - common
    - git
    - nginx
    - mariadb
    - php7
    - composer
    - redis
    - memcached
    - sexy-bash-prompt
    - magento2
